### ISSUE TITLE
Fix "Edit this Page" link

### ISSUE THREAD

**Issue by settermjd** [owncloud/docs-ui#17]

**Comment by tboerger** [comment]
This link is only broken for the core documentation, it is working fine for Desktop, Branded Clients and so on. I guess it's related to how the repository is referenced. The other docs are referenced by a GitHub URL while the core docs are referenced by a local path.

**Comment by mmattel** [comment]
core (server) has 
internally `server/modulename/pages/path/file.adoc` 
in html `server/modulename/path/file.html` 

**BUT:** this only applies for directly rendered files. Included files of any kind or images are treated differently. Included files are loaded and rendered as part of the html, so you only have the link to the hosting file and
images have the path `/server/module/_images/path/image.xxx`.

Wondering how that dynamic will be solved getting direct click access to the source depending of the origin and content...

Very personal note, my gut feeling tells me that the other doc modules currenty pointing to git will be directly integrated into docs, bringing more complication into the Edit this Page link path. But this is just my 2c.

**Comment by tboerger** [comment]
I don't get what you try to explain with that...

**Comment by mmattel** [comment]
It is quite easy,
- **All** pages have a button on the upper bar at the right side called "Edit this Page"
- This button should point directly to the location where you can edit exact the page shown
- My summary above highlights, this can´t be a static address but must be dynamically created depending on the page you are looking at (rules)
- If dynamic links based on rules can´t be done, the question is which link behind Edit this Page should be used.
- If it is static, I am asking myself, we already have links in the footer...

**Comment by tboerger** [comment]
All our other docs beside owncloud/docs are already working correctly. Just look at the branded clients, desktop, ios and android.

**Comment by mmattel** [comment]
Closing, fixed, link is working now
