### ISSUE TITLE
Update node version

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-ui#229]
`The engine "node" is incompatible with this module. Expected version "^10.12.0 || >=12.0.0". Got "11.15.0"`

Atm, the node version is as stated above 11.15.0
The current version (at the time of writing) is 12.20.0

The version should be upgraded so that bumps (normal and security) can pass CI

Note: readme should be improved, because there is still node v8 ...

@pmaier1 @micbar @phil-davis fyi (and request for help how to do that...)

**Comment by mmattel** [comment]
Info: the node image needs to be updated on server `owncloudci` where I have no access to...

**Comment by LukasHirt** [comment]
That might require more changes - when building docs locally they fail because the current used version of gulp is not compatible with `node > 11`.

**Comment by LukasHirt** [comment]
Anyway, what we did in different repos was using the latest version of `webhippie/nodejs`. I think we can do the same here.

**Comment by mmattel** [comment]
@LukasHirt maybe an idea to upgrade gulp from v3.x (as we currently use here) to v4.x ? and using a relatively recent version of node? see also the statement regarding end of maintainance of Gulp v3 below.

See: https://www.sitepoint.com/how-to-migrate-to-gulp-4/

And see: https://github.com/gulpjs/gulp/issues/2346#issuecomment-663189040
> **Gulp 3** probably doesn't work with new node but that version **is unmaintained as we released v4** about 3 years ago now - and node breaks things all the time.
Gulp 4 works on everything in the test matrix, though we are currently triaging a breaking change node core introduced in 12.18.3 that might cause some weirdness - though it should be an edge case of closing watchers in a running process and shouldn't affect most people.

**Comment by LukasHirt** [comment]
@mmattel Upgrading gulp definitely sounds like a good idea. I was also thinking for a while if it would make sense to introduce here webpack instead of gulp.

**Comment by mmattel** [comment]
@LukasHirt 
I think that we use webpack on other locations too but cant remember in detail. But in any case, I have very limited knowlege of both. So I just can say, "something" needs to be done by "somenone" to be futureproof :smile:

We have this node issue on other repros too and I would like to see a more or less unified use provided by one server serving different but not too far apart versions of node, so we can easily switch them by just defining it in the particular repro. Currently we have owncloudci, minio ect. Recently there was a "hickup" of an upgraded drone version on minio and builds were broken. It was relatively easy to "fix that" (thanks to @phil-davis) by just setting the working version to be downloaded... I think such a mechanism would be great for all rerpros using node just to switch the version used in the definition provided by a central server. What do you think?

**Comment by LukasHirt** [comment]
For now, I went with upgrading gulp as it is the fastest solution to unblock the newer version of node. Later I would really like to invest some time into experimenting with webpack here. I think it could be beneficial and as you @mmattel mentioned - we use it in other repos.

> I would like to see a more or less unified use provided by one server serving different but not too far apart versions of node, so we can easily switch them by just defining it in the particular repro.

I also like this approach with specific versions being used. AFAICT this is the case with our owncloudci images. Just would need to create tags for newer versions. For now, the solution with webhippie containers seems good enough to me though.
