### ISSUE TITLE
Alingment, location and size of the search field

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-ui#28]
As of 30.01.2019, the search field on docs.owncloud.org shows like that and has room for improvement:

Opera:
![image](https://user-images.githubusercontent.com/3321281/51993833-e9173600-24af-11e9-902c-04084880f56b.png)

Chrome:
![image](https://user-images.githubusercontent.com/3321281/51993909-01875080-24b0-11e9-9d87-36ad1f7836d9.png)

Edge:
![image](https://user-images.githubusercontent.com/3321281/51993958-1cf25b80-24b0-11e9-9d41-e2928687f892.png)

**Comment by tboerger** [comment]
Already solved
