### ISSUE TITLE
Design / Theme suggestions / discussion

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs-ui#31]
I browsed through our docs and found that it looks very monotone / grey-ish.

I was wondering if we could bring some color ( ownCloud Blue? ) in to it, to highlight some things, make the pages searchable.

**Comment by settermjd** [comment]
The theme already uses the ownCloud blue in the header and footer. What other areas, specifically, would you like to see changed, and how?

**Comment by voroyam** [comment]
Titles, code Blocks, general distinction areas between text and other text.

Like if you are scrolling through a document for example on the "occ" command. There is very little to look for, as things are black and grey. You don't know on the first glance where a section starts and where it ends, where an example starts and where it ends as everything is black and grey.
