### ISSUE TITLE
doc.owncloud.com searchbar is not responsive and therefore often not shown

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-ui#36]
## What Needs to be Documented?
Documentation search will not be shown in particular screen (resultion) settings.

1920x1080 150% (recommended stetting from Windows)
![image](https://user-images.githubusercontent.com/3321281/54923332-5375b100-4f0a-11e9-9347-68851edae6bb.png)
Search also does not show up in the hamburger menue

1920x1080 120% (not the recommended stetting from Windows)
![image](https://user-images.githubusercontent.com/3321281/54923268-2f19d480-4f0a-11e9-9b9e-ba89cfdc0fc4.png)

Same to Ubuntu with Linux Mint Desktop

## Why Should This Change Be Made? (Optional)
Make search resolution settings independent

## What Type Of Content Change Is This? (Optional)
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

@settermjd @tboerger @voroyam @ChrisEdS

**Comment by tboerger** [comment]
The search bar is not part of the responsive UI intentionally because we don't have a proper overlay layout for the search results. I don't think that this is something we will support until we got a proper ui based on a CSS framework that handles the dirty work.

**Comment by mmattel** [comment]
Thanks for you info. The follow up question raises, how to fix that everyone can see the field? I guess that the majority of people wont see the search field atm...

**Comment by tboerger** [comment]
At least people with an 800px screen will see the search bar after merging #37

**Comment by mmattel** [comment]
closing, #37 is merged, search is visible
