### ISSUE TITLE
Change to antora-highlightjs-extension (alternative for #692)

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-ui#775]
Referencing: [antora-highlightjs-extension](https://socket.dev/npm/package/antora-highlightjs-extension)
But this would implement `an old version of highlight.js`, see comment in link above.

As alternative to #692 (How to integrate prismjs as replacement for highlightjs (code highlighter))

**Comment by tbsbdr** [comment]
@AlexAndBear could you please have a look at this?
