### ISSUE TITLE
Edit this page... link doesn't work

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-ui#9]
When you build the docs, you get on every page an info to ``Edit this Page`` which is imho nonsense.

![image](https://user-images.githubusercontent.com/3321281/48204846-236aae80-e36b-11e8-9c2d-dd78ab6047d1.png)

The css can be found in ``src/css/toolbar.css``

The presentation in ``src/partials/toolbar.hbs`` with ``{page.editUrl}``. 
The template ``docs/modules/ROOT/pages/templates.adoc`` line ``#105`` is the only location where ``{page.editUrl}`` gets mentioned but it seems that it is nowhere set.

How to proceed - delete / comment out the (if possible) ``{page.editUrl}`` in ``src/partials/toolbar.hbs`` ?

Just for the record, I dug a bit to search how to comment something in a .hbs file. See https://stackoverflow.com/questions/15336142/how-to-use-comments-in-handlebar-templates

@settermjd

**Comment by settermjd** [comment]
At first glance, it seems worth implementing it, pointing it to the docs repo on GitHub, or removing it. I'm keen to implement it, so there are multiple ways for contributors to get involved.

**Comment by mmattel** [comment]
What I missed to document above (...) - the text "Edit Page) exists, but you currently get a million broken link error messages when running a broken link checker.

**Comment by mmattel** [comment]
Note, I was thinking about to use that ``Edit tho Page`` link but came to the conclusio that this is not a good idea in an professional environment. You present yourself as enterprise but then ask on every page if you want to edit it? That does not match. In the footer we already have a link: https://owncloud.org/community >Get involved< which on that page mentions to contribute to the documentation. That is imho enough.

Means remove ``Edit that Page``

**Comment by tboerger** [comment]
Please keep that link, that just shows that we welcome additions and fixes.

**Comment by mmattel** [comment]
Closing, fixed, link is working now
